// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc_9JqQXMyDNU-E0U7tx8gAwZOt-9WjkQ',
    appId: '1:870279073160:web:0f8e41cf62a5aa9950be3d',
    messagingSenderId: '870279073160',
    projectId: 'fasalguru-53a4b',
    authDomain: 'fasalguru-53a4b.firebaseapp.com',
    storageBucket: 'fasalguru-53a4b.firebasestorage.app',
    measurementId: 'G-DZVN7QMY1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-euqsIO4-Ynj0eBOwag2XlukcnZ8hGGs',
    appId: '1:870279073160:android:75ccff0120449c2450be3d',
    messagingSenderId: '870279073160',
    projectId: 'fasalguru-53a4b',
    storageBucket: 'fasalguru-53a4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKLOSrS-LOMYOw8fXjPQdsZ3wgVO5nPHM',
    appId: '1:870279073160:ios:33e769c661319ae550be3d',
    messagingSenderId: '870279073160',
    projectId: 'fasalguru-53a4b',
    storageBucket: 'fasalguru-53a4b.firebasestorage.app',
    iosBundleId: 'com.example.fasalguru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKLOSrS-LOMYOw8fXjPQdsZ3wgVO5nPHM',
    appId: '1:870279073160:ios:33e769c661319ae550be3d',
    messagingSenderId: '870279073160',
    projectId: 'fasalguru-53a4b',
    storageBucket: 'fasalguru-53a4b.firebasestorage.app',
    iosBundleId: 'com.example.fasalguru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc_9JqQXMyDNU-E0U7tx8gAwZOt-9WjkQ',
    appId: '1:870279073160:web:d2d67e2d6a74022a50be3d',
    messagingSenderId: '870279073160',
    projectId: 'fasalguru-53a4b',
    authDomain: 'fasalguru-53a4b.firebaseapp.com',
    storageBucket: 'fasalguru-53a4b.firebasestorage.app',
    measurementId: 'G-P3M3S8JKNJ',
  );
}
